# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "pwnbox"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y git libssl-dev libreadline-dev zlib1g-dev libc6-dev-i386
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    if ! [ -d ~/.rbenv ]
    then
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
      echo 'eval "$(rbenv init -)"' >>  ~/.bash_profile
      source ~/.bash_profile
    fi

    rbenv install 2.6.6
    rbenv global 2.6.6
    gem install pwntools
  SHELL
end
